# Customer Retention & Churn Analysis

## Future Interns – Data Science & Analytics Task 2

This project analyzes customer churn, retention patterns, customer lifetime, and factors associated with customer churn using Python and Power BI.

In [9]:
import pandas as pd

df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")

df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [10]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [12]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

In [13]:
df["TotalCharges"].isna().sum()

11

In [14]:
df[df["TotalCharges"].isna()][
    ["customerID", "tenure", "MonthlyCharges", "TotalCharges", "Churn"]
]

      customerID  tenure  MonthlyCharges  TotalCharges Churn
488   4472-LVYGI       0           52.55           NaN    No
753   3115-CZMZD       0           20.25           NaN    No
936   5709-LVOEQ       0           80.85           NaN    No
1082  4367-NUYAO       0           25.75           NaN    No
1340  1371-DWPAZ       0           56.05           NaN    No
3331  7644-OMVMY       0           19.85           NaN    No
3826  3213-VVOLG       0           25.35           NaN    No
4380  2520-SGTTA       0           20.00           NaN    No
5218  2923-ARZLG       0           19.70           NaN    No
6670  4075-WKNIU       0           73.35           NaN    No
6754  2775-SEFEE       0           61.90           NaN    No

In [15]:
df = df.dropna(subset=["TotalCharges"])

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   object
 1   gender            7032 non-null   object
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   object
 4   Dependents        7032 non-null   object
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   object
 7   MultipleLines     7032 non-null   object
 8   InternetService   7032 non-null   object
 9   OnlineSecurity    7032 non-null   object
 10  OnlineBackup      7032 non-null   object
 11  DeviceProtection  7032 non-null   object
 12  TechSupport       7032 non-null   object
 13  StreamingTV       7032 non-null   object
 14  StreamingMovies   7032 non-null   object
 15  Contract          7032 non-null   object
 16  PaperlessBilling  7032 non-null   object
 17  PaymentMethod     7032 non-null   object
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

In [17]:
df["Churn"].value_counts()

Churn
No     5163
Yes    1869
Name: count, dtype: int64

In [18]:
churn_rate = (df["Churn"] == "Yes").mean() * 100

churn_rate

26.578498293515356

In [19]:
df["Contract"].value_counts()

Contract
Month-to-month    3875
Two year          1685
One year          1472
Name: count, dtype: int64

In [20]:
contract_churn = pd.crosstab(
    df["Contract"],
    df["Churn"],
    normalize="index"
) * 100

contract_churn

Churn                  No        Yes
Contract
Month-to-month  57.290323  42.709677
One year        88.722826  11.277174
Two year        97.151335   2.848665

In [21]:
df["tenure"].describe()

count    7032.000000
mean       32.421786
std        24.545260
min         1.000000
25%         9.000000
50%        29.000000
75%        55.000000
max        72.000000
Name: tenure, dtype: float64

In [22]:
df["TenureGroup"] = pd.cut(
    df["tenure"],
    bins=[0, 12, 24, 48, 72],
    labels=["0-12 months", "13-24 months", "25-48 months", "49-72 months"]
)

In [23]:
df.groupby("TenureGroup", observed=True)["Churn"].value_counts(normalize=True) * 100

TenureGroup   Churn
0-12 months   No       52.321839
              Yes      47.678161
13-24 months  No       71.289062
              Yes      28.710938
25-48 months  No       79.611041
              Yes      20.388959
49-72 months  No       90.486824
              Yes       9.513176
Name: proportion, dtype: float64

In [24]:
df["MonthlyCharges"].describe()

count    7032.000000
mean       64.798208
std        30.085974
min        18.250000
25%        35.587500
50%        70.350000
75%        89.862500
max       118.750000
Name: MonthlyCharges, dtype: float64

In [25]:
df["ChargeGroup"] = pd.cut(
    df["MonthlyCharges"],
    bins=[0, 40, 80, float("inf")],
    labels=["Low", "Medium", "High"]
)

In [26]:
df.groupby("ChargeGroup", observed=True)["Churn"].value_counts(normalize=True) * 100

ChargeGroup  Churn
Low          No       88.318777
             Yes      11.681223
Medium       No       70.453649
             Yes      29.546351
High         No       66.003752
             Yes      33.996248
Name: proportion, dtype: float64

In [27]:
df["InternetService"].value_counts()

InternetService
Fiber optic    3096
DSL            2416
No             1520
Name: count, dtype: int64

In [28]:
df.groupby("InternetService", observed=True)["Churn"].value_counts(normalize=True) * 100

InternetService  Churn
DSL              No       81.001656
                 Yes      18.998344
Fiber optic      No       58.107235
                 Yes      41.892765
No               No       92.565789
                 Yes       7.434211
Name: proportion, dtype: float64

In [29]:
df["TechSupport"].value_counts()

TechSupport
No                     3472
Yes                    2040
No internet service    1520
Name: count, dtype: int64

In [30]:
df.groupby("TechSupport", observed=True)["Churn"].value_counts(normalize=True) * 100

TechSupport          Churn
No                   No       58.352535
                     Yes      41.647465
No internet service  No       92.565789
                     Yes       7.434211
Yes                  No       84.803922
                     Yes      15.196078
Name: proportion, dtype: float64

In [31]:
df["OnlineSecurity"].value_counts()

OnlineSecurity
No                     3497
Yes                    2015
No internet service    1520
Name: count, dtype: int64

In [32]:
df.groupby("OnlineSecurity", observed=True)["Churn"].value_counts(normalize=True) * 100

OnlineSecurity       Churn
No                   No       58.221333
                     Yes      41.778667
No internet service  No       92.565789
                     Yes       7.434211
Yes                  No       85.359801
                     Yes      14.640199
Name: proportion, dtype: float64

In [33]:
df["PaymentMethod"].value_counts()

PaymentMethod
Electronic check             2365
Mailed check                 1604
Bank transfer (automatic)    1542
Credit card (automatic)      1521
Name: count, dtype: int64

In [34]:
df.groupby("PaymentMethod", observed=True)["Churn"].value_counts(normalize=True) * 100

PaymentMethod              Churn
Bank transfer (automatic)  No       83.268482
                           Yes      16.731518
Credit card (automatic)    No       84.746877
                           Yes      15.253123
Electronic check           No       54.714588
                           Yes      45.285412
Mailed check               No       80.798005
                           Yes      19.201995
Name: proportion, dtype: float64

In [35]:
df.groupby("Churn")["TotalCharges"].mean()

Churn
No     2555.344141
Yes    1531.796094
Name: TotalCharges, dtype: float64

In [36]:
df.groupby("Churn")["tenure"].mean()

Churn
No     37.650010
Yes    17.979133
Name: tenure, dtype: float64

In [37]:
df.groupby("Churn")["tenure"].mean()

Churn
No     37.650010
Yes    17.979133
Name: tenure, dtype: float64

In [38]:
df.to_csv("Telco_Churn_Cleaned.csv", index=False)

In [39]:
import os
os.getcwd()

'C:\\Users\\hp'

In [40]:
import os
os.listdir()

['.anaconda',
 '.android',
 '.cache',
 '.conda',
 '.condarc',
 '.continuum',
 '.copilot',
 '.designer',
 '.ghcp-appmod',
 '.ghcp-appmod-java',
 '.gitconfig',
 '.gradle',
 '.ipynb_checkpoints',
 '.ipython',
 '.jdks',
 '.jupyter',
 '.lesshst',
 '.m2',
 '.matplotlib',
 '.ms-ad',
 '.Origin',
 '.qt-license',
 '.QtWebEngineProcess',
 '.vscode',
 '.vscode-shared',
 '9 aug.ipynb',
 'AndroidStudioProjects',
 'AppData',
 'Application Data',
 'C++ project.cpp',
 'Contacts',
 'Cookies',
 'Crop .ipynb',
 'Crop_recommendation.csv',
 'dataset (1).csv',
 'Documents',
 'Downloads',
 'Elevance_Task1_Sentiment_Escalation.ipynb',
 'emp sample.csv',
 'Favorites',
 'firstpro.ipynb',
 'FUTURE_DS_02.ipynb',
 'heart disease.ipynb',
 'heart.ipynb',
 'IdeaProjects',
 'index.html',
 'laptop_data.csv',
 'Links',
 'Local Settings',
 'Microsoft',
 'minmaxscaler.pkl',
 'ML Lab1.ipynb',
 'ML program.ipynb',
 'MLP.ipynb',
 'model.pkl',
 'Music',
 'My Documents',
 'MyProject',
 'NetHood',
 'noc_regions.csv',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{35cd45a2-6fb8-11f0-ae73-cc37ec95233e}.TM.blf',
 'NTUSER.DAT{35cd45a2-6fb8-11f0-ae73-cc37ec95233e}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{35cd45a2-6fb8-11f0-ae73-cc37ec95233e}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'Olympics-Exploratory-Analysis (EDA)-Copy1.ipynb',
 'Olympics-Exploratory-Analysis (EDA).ipynb',
 'Olympics.csv',
 'OneDrive',
 'pbitheme.txt',
 'Postman',
 'PrintHood',
 'puja.java',
 'PycharmProjects',
 'pythonpro.ipynb',
 'Recent',
 'rtu lab practical.ipynb',
 'sample superstore1.csv',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Superstore data.ipynb',
 'Telco_Churn_Cleaned.csv',
 'Templates',
 'Training.ipynb',
 'Untitled.ipynb',
 'untitled.txt',
 'Untitled1.ipynb',
 'untitled1.txt',
 'Untitled10.ipynb',
 'Untitled11.ipynb',
 'Untitled12.ipynb',
 'Untitled13.ipynb',
 'Untitled14.ipynb',
 'Untitled15.ipynb',
 'Untitled16.ipynb',
 'Untitled17.ipynb',
 'Untitled18.ipynb',
 'Untitled19.ipynb',
 'Untitled2.ipynb',
 'Untitled20.ipynb',
 'Untitled21.ipynb',
 'Untitled22.ipynb',
 'Untitled3.ipynb',
 'Untitled4.ipynb',
 'Untitled5.ipynb',
 'Untitled6.ipynb',
 'Untitled7.ipynb',
 'Untitled8.ipynb',
 'Untitled9.ipynb',
 'Videos',
 'WA_Fn-UseC_-Telco-Customer-Churn.csv',
 'web scrapping.ipynb',
 'winequality-red data.ipynb',
 'winequality-red.csv']